# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'QNRTCKitDemo' do
  pod 'QNRTCKit-iOS', :path =>'../QNRTCKit-iOS.podspec'
  pod 'PLPlayerKit', '3.4.3'
  pod 'Fabric', '1.7.2'
  pod 'Crashlytics', '3.9.3'
  pod 'Bugsnag', '5.15.4'
  pod 'MMMaterialDesignSpinner', '0.2.5'
  pod 'JGProgressHUD', '2.0.3'
  pod 'Masonry', '1.1.0'

  # pod 'QNRTCKit-iOS', :podspec =>'https://raw.githubusercontent.com/pili-engineering/QNRTC-iOS/master/QNRTCKit-iOS-universal.podspec'
  # pod "PLPlayerKit", :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/v3.4.3/PLPlayerKit-Universal.podspec'
end
